"""add roles to users table

Revision ID: 4d93591fb125
Revises: 53b745f7c323
Create Date: 2026-08-31 08:55:58.390780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d93591fb125'
down_revision: Union[str, Sequence[str], None] = '53b745f7c323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default=sa.text("'user'"), nullable=False))
    op.create_check_constraint('check_valid_user_roles', 'users', "role IN ('user', 'admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_valid_user_roles', 'users', type_='check')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
